mlp_dims: []
no_act: True
keep_embeds: [True, False] # position 0: Visual Embedding, position 1: Textual Embedding
initial_weights: 'ckpt_convnext_norm_emb/triplet_convnext-mlp_norm_emb.pth'
cosine: True
embedding_dim: 768